BaseURL = "https://sbackp.com"
DefaultContentLanguage = "en"
title = "SBACKP"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Web Analytics and MarTech" # Set a different text for the header on the home page
  subtitle = "Half thought-out ideas to made up problems"
  mainSections = ["post","posts"]
  logo = "img/avator-favicon-stag.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  since = "2023"
  baseURL = "https://sbackp.com"
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "SBACKP"
  website = "https://sbackp.com"
  email = "sbackp@gmail.com"
  facebook = "username"
  github = "sbackp"
  gitlab = "sbackp"
  bitbucket = "username"
  twitter = "sbackp"
  reddit = "sbackp"
  linkedin = "sbackp"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"
  500px = "username"
  codepen = "username"
  mastodon = "https://masto.measure.chat/@sbackp"
  kaggle = "username"
  weibo = "username"
  slack = "username"
  discord = "invite code (https://discord.gg/XXXXXXX)"
  strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
